### ISSUE TITLE
no works on react native 0.66.1

### ISSUE THREAD

**Issue by ghost** [slorber/react-native-scroll-into-view#41]
i'm following your example, and then updated react native on the last version, the scroll dosent work.

`TypeError: scrollView.getScrollResponder().scrollResponderScrollTo is not a function. (In 'scrollView.getScrollResponder().scrollResponderScrollTo({
                x: 0,
                y: newScrollY,
                animated: animated
              })', 'scrollView.getScrollResponder().scrollResponderScrollTo' is undefined)
`
